[phases.setup]
nixPkgs = ["nodejs_20", "npm-10_x", "openssl"]

[phases.install]
cmds = ["npm install"]

[phases.build]
cmds = ["tsc"]

[start]
cmd = "npx prisma generate && npx prisma db push --accept-data-loss && node dist/index.js"
